export const WORK = [
  { id:"softpatrol", t:"Softpatrol", cat:"Security Operations",
    img:"/softpatrol-dashboard.webp", alt:"/softpatrol-tracking.webp", tone:"#1B2F3E",
    d:"Guard patrol platform with live GPS tracking, patrol scheduling and incident reporting. Deployed to security firms across the UK.",
    metric:"1,000+ downloads", stack:["Flutter","Firebase","Google Maps"],
    link:"https://play.google.com/store/apps/details?id=com.computerfriends.softpatrol", ll:"Google Play" },
  { id:"tbms", t:"TBMS Driver", cat:"Transport Dispatch",
    img:"/tbms-dashboard.webp", alt:"/tbms-jobs.webp", tone:"#233240",
    d:"Taxi dispatch system for a UK operator. Real time job allocation, driver management and automated earnings reporting.",
    metric:"Live in UK operations", stack:["Flutter","WebSockets","Payments"] },
  { id:"jamgo", t:"JAMGO-CEE", cat:"Web Platform",
    img:"/task-management-dashboard.png", alt:"/analytics-reports-screen.png", tone:"#2A3B47",
    d:"Full stack web platform for an international client with a focus on performance and organic search visibility.",
    metric:"Live in production", stack:["Next.js","Node.js","Postgres"],
    link:"https://jamgocee.com", ll:"Visit site" },
  { id:"ai", t:"AI Support Platform", cat:"Artificial Intelligence",
    img:"/social-reviews-ratings.png", alt:"/team-collaboration-interface.png", tone:"#141F29",
    d:"Multi tenant AI assistant with custom knowledge bases, conversation memory and multi channel deployment.",
    metric:"60% fewer support tickets", stack:["OpenAI","Node.js","React"] },
  { id:"restaurant", t:"Restaurant OS", cat:"Hospitality",
    img:"/food-delivery-app-screen.png", alt:"/ar-menu-scanning-interface.png", tone:"#2C4A5E",
    d:"QR table ordering, kitchen display system and real time order tracking with full POS integration.",
    metric:"Multi location rollout", stack:["Flutter","Firebase","POS"] },
  { id:"chauffeur", t:"Chauffeur Booking", cat:"Luxury Transport",
    img:"/tbms-tablet.webp", alt:"/restaurant-discovery-map.png", tone:"#3A5468",
    d:"Premium chauffeur booking with live driver tracking, dynamic pricing and corporate account management.",
    metric:"4.8 star rating", stack:["Flutter","Stripe","Maps"] },
  { id:"fitness", t:"FitLife Pro", cat:"Health & Fitness",
    img:"/fitness-app-interface.png", alt:"/fitness-app-workout.png", tone:"#28414F",
    d:"Cross platform fitness tracking with personalised workout plans, progress analytics and social features.",
    metric:"Cross platform", stack:["Flutter","Firebase","REST API"] },
  { id:"crypto", t:"CryptoVault", cat:"FinTech",
    img:"/crypto-wallet-interface.png", alt:"/trading-interface.png", tone:"#1B2F3E",
    d:"Cryptocurrency portfolio tracker with live market data, price alerts and secure wallet management.",
    metric:"Real time data", stack:["Flutter","WebSockets","Secure Storage"] },
]

export const CLIENTS = [
  { id:"pk", name:"DevelopersTech", role:"Studio headquarters", city:"Lahore, Pakistan", flag:"PK",
    x:70.5, y:41, color:"#4A7A96", hq:true,
    review:"Founded in Lahore in 2023. Five years of engineering experience serving clients across the UK, UAE, Europe and the US.", project:"Head office" },
  { id:"uk1", name:"claudz85", role:"Flutter application", city:"United Kingdom", flag:"UK",
    x:47.5, y:25, color:"#6FA0BC",
    review:"Good experience overall. The developer communicated professionally throughout, understood the scope well and delivered within the agreed timeline. Cooperative and responsive in addressing all feedback.", project:"Flutter mobile app", fiverr:true },
  { id:"uk2", name:"UK Transport Operator", role:"Operations director", city:"United Kingdom", flag:"UK",
    x:46.2, y:23.5, color:"#6FA0BC",
    review:"Sanwal delivered our Flutter app ahead of schedule. The real time tracking worked flawlessly on launch day, something our previous vendor failed to achieve in six months.", project:"TBMS dispatch system" },
  { id:"us1", name:"trudef", role:"Returning client, 4 projects", city:"United States", flag:"US",
    x:22, y:33, color:"#B8935F",
    review:"Working with Sanwal has been an excellent experience from start to finish. He is extremely professional, reliable, and always communicates clearly. We are returning customers because of the consistency and quality of his work.", project:"Flutter app and Figma design", fiverr:true },
  { id:"us2", name:"trudef", role:"Verified buyer", city:"United States", flag:"US",
    x:24.5, y:36, color:"#B8935F",
    review:"Sanwal has been outstanding to work with. He is dedicated, communicates clearly, and does not stop until the customer is fully satisfied. Any time changes were needed, he made them quickly and kept us updated.", project:"Mobile app development", fiverr:true },
  { id:"ae", name:"Ahmed R.", role:"Founder and CEO", city:"Dubai, UAE", flag:"AE",
    x:60.5, y:38, color:"#3A9B6E",
    review:"We needed a complex dispatch system built to enterprise standards. DevelopersTech understood our requirements better than we did. Clean code, clean handoff, zero issues post launch.", project:"Taxi dispatch system" },
  { id:"de", name:"Michael K.", role:"Product owner", city:"Germany", flag:"DE",
    x:51.5, y:25.5, color:"#7B5EA7",
    review:"Hired Sanwal for a Flutter project and came back three more times. Excellent communicator, fast delivery, and the quality of the code is something I can actually maintain.", project:"Flutter apps, 3 projects", fiverr:true },
  { id:"in", name:"Priya M.", role:"Chief technology officer", city:"India", flag:"IN",
    x:66, y:40, color:"#D97706",
    review:"The AI chatbot integration Sanwal built for our platform increased user engagement significantly. He knew exactly how to work with the OpenAI APIs, production ready from day one.", project:"AI chatbot platform" },
]

export const SERVICES = [
  { n:"01", t:"Mobile Applications", d:"Flutter, native Android and iOS. One codebase, four platforms, production grade from day one.", items:["Flutter","Android","iOS","Cross Platform"] },
  { n:"02", t:"Web and Enterprise", d:"Scalable web platforms, multi tenant SaaS, internal dashboards and business systems.", items:["Web Apps","SaaS","ERP and CRM","Dashboards"] },
  { n:"03", t:"Artificial Intelligence", d:"Production AI on OpenAI, Claude and Gemini. Not demos, systems that hold up under load.", items:["AI Apps","Chatbots","Automation","API Work"] },
  { n:"04", t:"Industry Systems", d:"Dispatch, monitoring and booking software built from real operational experience.", items:["Dispatch","Monitoring","Booking","Fleet"] },
]
